### ISSUE TITLE
Práctica  diseño de estructura de librería dll

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipoolaxd#1]
[practica 5.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipoolaxd/files/14705495/practica.5.pdf)

**Comment by ElisabetRD** [comment]
18.4% tienen 12 ilustraciones

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
